# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.cache/wt [current_project]
set_property parent.project_path E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Desktop/diceModules/MODS/MODS.srcs/sources_1/new/LFSR.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/sources_1/imports/Desktop/Oled_Display.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/anodeIdx.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/boxChooser.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/counter1s.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/counter2s.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Desktop/diceModules/MODS/MODS.srcs/sources_1/new/counterFiveHz.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Desktop/diceModules/MODS/MODS.srcs/sources_1/new/counterOneHz.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/debouncer.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/diceModule.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/sources_1/new/flexible_clock.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/gameOverScreen.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/gameState.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/sources_1/new/pixel_index_to_cartesian.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/player1_movementFSM.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/player2_movementFSM.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/player3_movementFSM.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/player4_movementFSM.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/powerUpIcons.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/powerUpMenu.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/printReviveMessage.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/renderDoubleDice.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/renderDoubleJump.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/renderPlayerBox.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/renderReviveIcon.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/renderSkipTurn.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/reviveChoice.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/reviveMenu.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/segementChoiceDisplay.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/selectPowerUp.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/simple_game_grid.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/soundCounter.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/startScreen.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/topMessage.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/Downloads/powerUps.xpr/MODS/MODS.srcs/sources_1/new/variable_clk.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/winScreen.v
  E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/new/main.v
}
read_vhdl -library xil_defaultlib E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/sources_1/imports/everything/Audio_Output.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/constrs_1/imports/EE2026/Basys3_Master.xdc
set_property used_in_implementation false [get_files E:/Stuff/School/y2s2/ee2026/Project/ludo_game/final/EE2026_final_project/EE2026_final_project.srcs/constrs_1/imports/EE2026/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
